# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository under GitHub workspace
      - uses: actions/checkout@v3

      # Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug

      # Install dependencies
      - name: Install
        run: make install

      # Run linter
      - name: Run linter
        run: make lint

      # - name: Install Xdebug
      #   run: sudo apt-get install php-xdebug

      # Run setup before running tests and coverage
      - name: Setup environment
        run: make setup

      - name: Debug Xdebug Status
        run: |
          php -m
          XDEBUG_MODE=coverage php artisan test --coverage-clover build/logs/clover.xml -v
        
      - name: Check Xdebug installation
        run: php -m | grep xdebug

      - name: Run tests with coverage
        run: XDEBUG_MODE=coverage php artisan test --coverage-clover build/logs/clover.xml

      
      # Publish coverage to Code Climate (after running tests)
      - name: Code Climate Reporter (after-build)
        uses: paambaati/codeclimate-action@v5
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}